# Generated by Django 3.1.6 on 2021-08-24 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrineAnalysisWaitingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_request', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('albumine', models.BooleanField(default=False)),
                ('blood', models.BooleanField(default=False)),
                ('chemo_leukocyte', models.BooleanField(default=False)),
                ('glucose', models.BooleanField(default=False)),
                ('PH', models.BooleanField(default=False)),
                ('nitrate', models.BooleanField(default=False)),
                ('urobilonogen', models.BooleanField(default=False)),
                ('ketone', models.BooleanField(default=False)),
                ('bilirubin', models.BooleanField(default=False)),
                ('specific_gravity', models.BooleanField(default=False)),
                ('microscopy_leukocyte', models.BooleanField(default=False)),
                ('erythrocyte', models.BooleanField(default=False)),
                ('yeast', models.BooleanField(default=False)),
                ('bacteria', models.SmallIntegerField(null=True)),
                ('squamous_epithelial_cell', models.BooleanField(default=False)),
                ('hyaline_cast', models.BooleanField(default=False)),
                ('granular_cast', models.BooleanField(default=False)),
                ('WBC_casts', models.BooleanField(default=False)),
                ('RBC_cast', models.BooleanField(default=False)),
                ('uric_acid', models.BooleanField(default=False)),
                ('calcium_oxalate', models.BooleanField(default=False)),
                ('triple_phosphate', models.BooleanField(default=False)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urine_rqst_requested_by', to='accounts.staff')),
                ('requested_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urine_rqst_requested_to', to='accounts.staff')),
            ],
        ),
        migrations.CreateModel(
            name='HematologyWaitingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_request', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('date_of_report', models.DateTimeField(null=True)),
                ('CBC', models.BooleanField(default=False)),
                ('BE', models.BooleanField(default=False)),
                ('TWBC', models.BooleanField(default=False)),
                ('differential', models.BooleanField(default=False)),
                ('neutrophil', models.BooleanField(default=False)),
                ('lymphocyte', models.BooleanField(default=False)),
                ('eocynophil', models.BooleanField(default=False)),
                ('basophiles', models.BooleanField(default=False)),
                ('monocyt', models.BooleanField(default=False)),
                ('haemoglobin', models.BooleanField(default=False)),
                ('hemo_TCRIT', models.BooleanField(default=False)),
                ('MCV', models.BooleanField(default=False)),
                ('MCH', models.BooleanField(default=False)),
                ('MCHC', models.BooleanField(default=False)),
                ('RBC', models.BooleanField(default=False)),
                ('RBC_morphology', models.BooleanField(default=False)),
                ('platlet_count', models.BooleanField(default=False)),
                ('EST', models.BooleanField(default=False)),
                ('bleeding_time_test', models.BooleanField(default=False)),
                ('clot_retraction', models.BooleanField(default=False)),
                ('coagulation_time', models.BooleanField(default=False)),
                ('prothrombin_time', models.BooleanField(default=False)),
                ('PTT', models.BooleanField(default=False)),
                ('FBS_RBS', models.BooleanField(default=False)),
                ('blood_group', models.BooleanField(default=False)),
                ('fibrinogen', models.BooleanField(default=False)),
                ('coombs_test', models.BooleanField(default=False)),
                ('CD4', models.BooleanField(default=False)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hematology_rqst_requested_by', to='accounts.staff')),
                ('requested_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hematology_rqst_requested_to', to='accounts.staff')),
            ],
        ),
    ]
