# Generated by Django 3.1.6 on 2021-08-19 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0016_auto_20210819_0353'),
        ('accounts', '0003_staff_num_waiting'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoolExaminationWaitingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_request', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('parasites', models.BooleanField(default=False)),
                ('pus_cell', models.BooleanField(default=False)),
                ('red_blood_cell', models.BooleanField(default=False)),
                ('yeast_cell', models.BooleanField(default=False)),
                ('occult_blood_test', models.BooleanField(default=False)),
                ('h_pylory_stool_ag_test', models.BooleanField(default=False)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stool_waiting_requested_by', to='accounts.staff')),
                ('requested_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stool_waiting_requested_to', to='accounts.staff')),
            ],
        ),
    ]
