# Generated by Django 3.2.5 on 2021-08-24 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lab_technician', '0001_initial'),
        ('patient', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urineanalysiswaitinglist',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient'),
        ),
        migrations.AddField(
            model_name='urineanalysiswaitinglist',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urine_rqst_requested_by', to='accounts.staff'),
        ),
        migrations.AddField(
            model_name='urineanalysiswaitinglist',
            name='requested_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urine_rqst_requested_to', to='accounts.staff'),
        ),
        migrations.AddField(
            model_name='hematologywaitinglist',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.hospital'),
        ),
        migrations.AddField(
            model_name='hematologywaitinglist',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient'),
        ),
        migrations.AddField(
            model_name='hematologywaitinglist',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hematology_rqst_requested_by', to='accounts.staff'),
        ),
        migrations.AddField(
            model_name='hematologywaitinglist',
            name='requested_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hematology_rqst_requested_to', to='accounts.staff'),
        ),
    ]
