# Generated by Django 3.1.6 on 2021-08-20 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_staff_num_waiting'),
        ('patient', '0016_auto_20210819_0353'),
        ('lab_technician', '0002_auto_20210820_0242'),
    ]

    operations = [
        migrations.CreateModel(
            name='HematologyWaitingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_request', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('date_of_report', models.DateTimeField(null=True)),
                ('CBC', models.BooleanField(default=False)),
                ('BE', models.BooleanField(default=False)),
                ('TWBC', models.BooleanField(default=False)),
                ('differential', models.BooleanField(default=False)),
                ('neutrophil', models.BooleanField(default=False)),
                ('lymphocyte', models.BooleanField(default=False)),
                ('eocynophil', models.BooleanField(default=False)),
                ('basophiles', models.BooleanField(default=False)),
                ('monocyt', models.BooleanField(default=False)),
                ('haemoglobin', models.BooleanField(default=False)),
                ('hemo_TCRIT', models.BooleanField(default=False)),
                ('MCV', models.BooleanField(default=False)),
                ('MCH', models.BooleanField(default=False)),
                ('MCHC', models.BooleanField(default=False)),
                ('RBC', models.BooleanField(default=False)),
                ('RBC_morphology', models.BooleanField(default=False)),
                ('platlet_count', models.BooleanField(default=False)),
                ('EST', models.BooleanField(default=False)),
                ('bleeding_time_test', models.BooleanField(default=False)),
                ('clot_retraction', models.BooleanField(default=False)),
                ('coagulation_time', models.BooleanField(default=False)),
                ('prothrombin_time', models.BooleanField(default=False)),
                ('PTT', models.BooleanField(default=False)),
                ('FBS_RBS', models.BooleanField(default=False)),
                ('blood_group', models.BooleanField(default=False)),
                ('fibrinogen', models.BooleanField(default=False)),
                ('coombs_test', models.BooleanField(default=False)),
                ('CD4', models.BooleanField(default=False)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hematology_rqst_requested_by', to='accounts.staff')),
                ('requested_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hematology_rqst_requested_to', to='accounts.staff')),
            ],
        ),
    ]
