# Generated by Django 3.2.5 on 2021-08-25 13:45

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_pharmacy_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='house_no',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=50)),
        ),
    ]
