# Generated by Django 3.1.6 on 2021-08-15 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210812_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='num_waiting',
            field=models.IntegerField(default=0),
        ),
    ]
