# Generated by Django 3.1.6 on 2021-08-14 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy_admin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pharmacist',
        ),
    ]
