# Generated by Django 3.1.6 on 2021-08-14 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210812_1037'),
        ('patient', '0003_auto_20210814_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xrayexamination',
            name='requested_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xray_reported_to', to='accounts.staff'),
        ),
    ]
