# Generated by Django 3.1.6 on 2021-08-14 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_auto_20210814_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='xrayexamination',
            name='finding_and_diagnosis',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='xrayexamination',
            name='examination_requested',
            field=models.TextField(),
        ),
    ]
