# Generated by Django 3.1.6 on 2021-08-16 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_staff_num_waiting'),
        ('patient', '0006_auto_20210815_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='ultrasound',
            name='requested_to',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ultrasound_requested_to', to='accounts.staff'),
        ),
    ]
