# Generated by Django 3.1.6 on 2021-08-16 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_staff_num_waiting'),
        ('patient', '0008_auto_20210816_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ultrasound',
            name='reported_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ultrasound_reported_by', to='accounts.staff'),
        ),
    ]
