# Generated by Django 3.1.6 on 2021-08-16 19:22

from django.db import migrations, models
import patient.models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0009_auto_20210816_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ultrasound',
            name='ultra_sound_image',
            field=models.ImageField(blank=True, null=True, upload_to=patient.models.filepath),
        ),
        migrations.AlterField(
            model_name='xrayexamination',
            name='x_ray_image',
            field=models.ImageField(blank=True, null=True, upload_to=patient.models.filepath),
        ),
    ]
