# Generated by Django 3.1.6 on 2021-08-16 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0010_auto_20210816_2222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xrayexamination',
            name='x_ray_report',
        ),
        migrations.AlterField(
            model_name='ultrasound',
            name='ultra_sound_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='xrayexamination',
            name='x_ray_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
