# Generated by Django 3.1.6 on 2021-08-16 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0011_auto_20210816_2344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ultrasound',
            name='reported_by',
        ),
    ]
