# Generated by Django 3.1.6 on 2021-08-18 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_staff_num_waiting'),
        ('patient', '0012_remove_ultrasound_reported_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='hematology',
            name='requested_to',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='hematology_requested_to', to='accounts.staff'),
        ),
        migrations.AddField(
            model_name='stoolexamination',
            name='requested_to',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='stool_requested_to', to='accounts.staff'),
        ),
        migrations.AddField(
            model_name='urineanalysis',
            name='requested_to',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='urine_requested_to', to='accounts.staff'),
        ),
        migrations.AlterField(
            model_name='hematology',
            name='date_of_request',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='stoolexamination',
            name='date_of_request',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
