# Generated by Django 3.1.6 on 2021-08-18 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_staff_num_waiting'),
        ('patient', '0013_auto_20210819_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hematology',
            name='requested_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hematology_requested_to', to='accounts.staff'),
        ),
        migrations.AlterField(
            model_name='stoolexamination',
            name='requested_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stool_requested_to', to='accounts.staff'),
        ),
        migrations.AlterField(
            model_name='urineanalysis',
            name='requested_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urine_requested_to', to='accounts.staff'),
        ),
    ]
