# Generated by Django 3.1.6 on 2021-08-19 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0014_auto_20210819_0207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urineanalysis',
            old_name='granular_cas',
            new_name='granular_cast',
        ),
        migrations.RemoveField(
            model_name='urineanalysis',
            name='parasites',
        ),
        migrations.RemoveField(
            model_name='urineanalysis',
            name='pus_cell',
        ),
        migrations.RemoveField(
            model_name='urineanalysis',
            name='red_blood_cell',
        ),
    ]
