# Generated by Django 3.1.6 on 2021-08-21 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0016_auto_20210819_0353'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='bought_on_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
