# Generated by Django 3.1.6 on 2021-08-22 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_staff_num_waiting'),
        ('patient', '0017_auto_20210821_1705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='date',
            new_name='prescription_date',
        ),
        migrations.AddField(
            model_name='prescription',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='frequency_perday',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='medication_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='pharmacy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.pharmacy'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.DeleteModel(
            name='Medication',
        ),
    ]
