from django.db import models

# Create your models here.
from accounts.models import User, Staff, Hospital
from patient.models import Patient


class UrineAnalysisWaitingList(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    requested_by = models.ForeignKey(Staff, on_delete=models.CASCADE, related_name='urine_rqst_requested_by')
    requested_to = models.ForeignKey(Staff, on_delete=models.CASCADE, related_name='urine_rqst_requested_to')
    hospital = models.ForeignKey(Hospital, on_delete=models.CASCADE)
    date_of_request = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=50, default='pending')
    albumine = models.BooleanField(default=False)
    blood = models.BooleanField(default=False)
    chemo_leukocyte = models.BooleanField(default=False)
    glucose = models.BooleanField(default=False)
    PH = models.BooleanField(default=False)
    nitrate = models.BooleanField(default=False)
    urobilonogen = models.BooleanField(default=False)
    ketone = models.BooleanField(default=False)
    bilirubin = models.BooleanField(default=False)
    specific_gravity = models.BooleanField(default=False)
    microscopy_leukocyte = models.BooleanField(default=False)
    erythrocyte = models.BooleanField(default=False)
    yeast = models.BooleanField(default=False)
    bacteria = models.SmallIntegerField(null=True)
    squamous_epithelial_cell = models.BooleanField(default=False)
    hyaline_cast = models.BooleanField(default=False)
    granular_cast = models.BooleanField(default=False)
    WBC_casts = models.BooleanField(default=False)
    RBC_cast = models.BooleanField(default=False)
    uric_acid = models.BooleanField(default=False)
    calcium_oxalate = models.BooleanField(default=False)
    triple_phosphate = models.BooleanField(default=False)


class HematologyWaitingList(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    requested_by = models.ForeignKey(Staff, on_delete=models.CASCADE, related_name='hematology_rqst_requested_by')
    requested_to = models.ForeignKey(Staff, on_delete=models.CASCADE, related_name='hematology_rqst_requested_to')
    hospital = models.ForeignKey(Hospital, on_delete=models.CASCADE)
    date_of_request = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=50, default='pending')
    date_of_report = models.DateTimeField(null=True)
    CBC = models.BooleanField(default=False)
    BE = models.BooleanField(default=False)
    TWBC = models.BooleanField(default=False)
    differential = models.BooleanField(default=False)
    neutrophil = models.BooleanField(default=False)
    lymphocyte = models.BooleanField(default=False)
    eocynophil = models.BooleanField(default=False)
    basophiles = models.BooleanField(default=False)
    monocyt = models.BooleanField(default=False)
    haemoglobin = models.BooleanField(default=False)
    hemo_TCRIT = models.BooleanField(default=False)
    MCV = models.BooleanField(default=False)
    MCH = models.BooleanField(default=False)
    MCHC = models.BooleanField(default=False)
    RBC = models.BooleanField(default=False)
    RBC_morphology = models.BooleanField(default=False)
    platlet_count = models.BooleanField(default=False)
    EST = models.BooleanField(default=False)
    bleeding_time_test = models.BooleanField(default=False)
    clot_retraction = models.BooleanField(default=False)
    coagulation_time = models.BooleanField(default=False)
    prothrombin_time = models.BooleanField(default=False)
    PTT = models.BooleanField(default=False)
    FBS_RBS = models.BooleanField(default=False)
    blood_group = models.BooleanField(default=False)
    fibrinogen = models.BooleanField(default=False)
    coombs_test = models.BooleanField(default=False)
    CD4 = models.BooleanField(default=False)
