# Generated by Django 3.2.5 on 2021-08-24 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physician', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='department',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
