# Generated by Django 3.1.6 on 2021-08-12 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physician', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='health_problem_identified_in_detail',
            field=models.TextField(),
        ),
    ]
