# Generated by Django 3.1.6 on 2021-08-25 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physician', '0002_appointment_appointment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_time',
            field=models.TimeField(null=True),
        ),
    ]
