# Generated by Django 3.1.6 on 2021-08-12 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physician', '0002_auto_20210812_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='health_problem_identified_in_detail',
            field=models.TextField(null=True),
        ),
    ]
