# Generated by Django 3.1.6 on 2021-08-12 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physician', '0003_auto_20210812_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientwaitinglist',
            name='approval_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
