# Generated by Django 3.1.6 on 2021-08-12 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physician', '0004_patientwaitinglist_approval_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientwaitinglist',
            name='approval_time',
            field=models.DateTimeField(null=True),
        ),
    ]
