# Generated by Django 3.1.6 on 2021-08-14 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physician', '0006_patientwaitinglist_physician_speciality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientwaitinglist',
            name='physician_speciality',
            field=models.CharField(max_length=50),
        ),
    ]
